AWSTemplateFormatVersion: '2010-09-09'
Description: "Compute stack for FridayHIIT VPC"

Resources:
  PublicEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !Ref PublicSecurityGroup
      ImageId: ami-0e86e20dae9224db8
      KeyName: EC2Key
  
  PrivateEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      SubnetId: !Ref PrivateSubnet
      SecurityGroupIds:
        - !Ref PrivateSecurityGroup
      ImageId: ami-0e86e20dae9224db8
      KeyName: EC2Key