AWSTemplateFormatVersion: '2010-09-09'
Description: "Compute stack for FridayHIIT VPC"

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
    Description: EC2 Instance Type

  ImageId:
    Type: String
    Description: "AMI ID for EC2"

Resources:
  PublicEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !Ref PublicSecurityGroup
      ImageId: !Ref ImageId
      KeyName: EC2Key
  
  PrivateEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      SubnetId: !Ref PrivateSubnet
      SecurityGroupIds:
        - !Ref PrivateSecurityGroup
      ImageId: !Ref ImageId
      KeyName: EC2Key