AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Template for FridayHIIT VPC"

Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: FridayHIIT-VPC

Outputs:
  VPCID:
    Description: 'VPC ID'
    Value: !Ref VPC
    Export:
      Name: !Sub '${AWS::StackName}-VPCID'