- ParameterKey: VPCName
  ParameterValue: MyVPC

- ParameterKey: InstanceType
  ParameterValue: t2.micro

- ParameterKey: CidrBlock
  ParameterValue: 10.0.0.0/16

- ParameterKey: PublicSubnetCidrBlock
  ParameterValue: 10.0.1.0/24

- ParameterKey: PrivateSubnetCidrBlock
  ParameterValue: 10.0.2.0/24
